**Note: In Data Science googling is a very important skill. If you find some difficulties to solve the problem, google it and try to find some clues to solve.**

In [ ]:
import numpy as np

###`Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [ ]:
#Code here
a = np.zeros(10,dtype=int)
a[4] = 1
print(a)


[0 0 0 0 1 0 0 0 0 0]


In [ ]:
#using array()
np.array([0,0,0,0,1,0,0,0,0,0])

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

###`Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [ ]:
#Code here
a = int(input())
b = int(input())
random = np.random.random((a,b))
print(random)
average = np.mean(random)
print("avg",average)

2
3
[[0.76575342 0.12253291 0.58765652]
 [0.92951677 0.94864866 0.91053677]]
avg 0.7107741733595915


###`Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [ ]:
#Code here
import numpy as np

def create_border_array(a,b):
  array = np.zeros((a,b),dtype=int)

  #set border
  array[0,:] = 1
  array[-1,:] = 1
  array[:,0] = 1
  array[:,-1] = 1

  return array

a = int(input("enter rows"))
b = int(input("enter column"))

border_array = create_border_array(a,b)
print(border_array)

enter rows4
enter column4
[[1 1 1 1]
 [1 0 0 1]
 [1 0 0 1]
 [1 1 1 1]]


###`Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [ ]:
#Code here
np.linspace(0.1,0.9,10)

array([0.1       , 0.18888889, 0.27777778, 0.36666667, 0.45555556,
       0.54444444, 0.63333333, 0.72222222, 0.81111111, 0.9       ])

In [ ]:
vector  = np.linspace(0,1,10,endpoint=False)
print(vector)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


###`Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [ ]:
#Code here
"""identity matrix of shape (3, 4) is not possible because an identity matrix is
a square matrix with the same number of rows and columns.
If you're looking to create a matrix of shape (3, 4) with ones on the diagonal
 and zeros elsewhere, you can use np.eye()"""
import numpy as np
identity_like_matrix = np.eye(3, 4)

print(identity_like_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [ ]:
#Code here
# Identity matricx is a square mattrix, means no of rows and columns will always be same.
# Here shape given 3,4 so identuty matrix not possible.

#Identy matrix of size 3-- 3X3
np.eye(3)

#Identy matrix of size 4-- 4X4
np.identity(4)

# eye and identity are same.

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

###`Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [ ]:
z = np.zeros((5,5))
z += np.arange(5)
z

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [ ]:
#Code here
matrix = np.array([np.arange(5)]*5)
print(matrix)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [ ]:
#list comprehension
np.array([list(range(5))]*5)

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [ ]:
#using loop
np.zeros((5,5),dtype=int)
for i in range(5):
  matrix[i] = np.arange(5)
print(matrix)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


###`Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3])
```


In [ ]:
#code here
random_vector = np.random.randint(1,101,size=(10,2))
given_point = np.array([2,3])

distance = np.sqrt(np.sum((random_vector - given_point)**2,axis=1)).astype(int)
print("Random Vector:")
print(random_vector)
print("\nGiven Point:")
print(given_point)
print("\nDistances from Given Point:")
print(distance)

Random Vector:
[[42 10]
 [99 62]
 [78 10]
 [28 95]
 [99 89]
 [74 24]
 [45 56]
 [ 1  2]
 [47 14]
 [77  9]]

Given Point:
[2 3]

Distances from Given Point:
[ 40 113  76  95 129  75  68   1  46  75]


###`Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [ ]:
np.unravel_index(100, (6,7,8))

(1, 5, 4)

### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [ ]:
import numpy as np
a = input(" enter the space-separated numbers")
a = a.split()
arr = np.array(a,dtype=float)
rev_array = arr[::-1]
print(rev_array)

 enter the space-separated numbers1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [ ]:
import numpy as np
count = 0
a = np.array([1,2])
for i in a:
  count+=1
print("element_count : ", count)

element_count :  2


In [ ]:
#2nd way using size
a = np.array([])
count = a.size
print("element_count : ",count)

element_count :  0


### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [ ]:
#Code here
def softmax(arr):
  if type(arr) != np.ndarray:
     raise TypeError("Requires Numpy Array")
  elif arr.ndim>1:
       raise TypeError("Requires Numpy Array")
  s = np.sum(np.exp(arr))
  return np.exp(arr)
softmax(np.array([86.03331084, 37.7285648,  48.64908087, 87.16563062, 38.40852563, 37.20006318]))

array([2.31095856e+37, 2.42832887e+16, 1.34284959e+21, 7.17054870e+37,
       4.79303653e+16, 1.43146972e+16])

### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [ ]:
def vertical_stack(*args):
    for i in args:
        if type(i) != np.ndarray:
            raise TypeError("Requires Numpy Array")
    return np.vstack(args)

a = np.arange(10).reshape(2, -1)
print("a=",a)
b = np.repeat(1, 10).reshape(2, -1)
print("b=",b)
print(vertical_stack(a,b))
c = np.random.random((2,5))
print("c=", c)
vertical_stack(a,b,c)

a= [[0 1 2 3 4]
 [5 6 7 8 9]]
b= [[1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
c= [[0.53425934 0.5939379  0.41881582 0.72943505 0.88708872]
 [0.29991042 0.98255274 0.35440508 0.07288093 0.05544008]]


array([[0.        , 1.        , 2.        , 3.        , 4.        ],
       [5.        , 6.        , 7.        , 8.        , 9.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ],
       [0.53425934, 0.5939379 , 0.41881582, 0.72943505, 0.88708872],
       [0.29991042, 0.98255274, 0.35440508, 0.07288093, 0.05544008]])

In [ ]:
#Coder here
import numpy as np
def vertical_stack(*args):
  array = []
  for arg in args:
    if isinstance(arg,np.ndarray):
      array.append(arg)
    else:
      raise ValueError("All argument must be NumPy arrays.")
  stacked_array = np.vstack(array)
  return stacked_array

In [ ]:
# Create the arrays
a = np.array([[0, 1, 2, 3, 4],
              [5, 6, 7, 8, 9]])

b = np.array([[1, 1, 1, 1, 1],
              [1, 1, 1, 1, 1]])

c = np.array([[0.10117373, 0.1677244, 0.73764059, 0.83166097, 0.48985695],
              [0.44581567, 0.13502419, 0.55692335, 0.16479622, 0.61193593]])

# Use the function to vertically stack the arrays
result = vertical_stack(a, b, c)

# Print the resulting stacked array
print(result)

[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]


### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [ ]:
#Code here
def date_array(start:str,end:str):
  if type(start) != str or type(end) != str:
     raise TypeError("Both start and end should be strings.")

  end = end.split("-")
  end_last = int(end[-1]) + 1
  if end_last <10:
    end[-1]= f'0{end_last}'
  else:
    end[-1] = str(end_last)
  end = "-".join(end)
  return np.arange(start, end, dtype="datetime64[D]")    # Use arange() to generate all dates between start and end

result = date_array(start = '2020-11-09', end = '2020-11-25')
print(result)



['2020-11-09' '2020-11-10' '2020-11-11' '2020-11-12' '2020-11-13'
 '2020-11-14' '2020-11-15' '2020-11-16' '2020-11-17' '2020-11-18'
 '2020-11-19' '2020-11-20' '2020-11-21' '2020-11-22' '2020-11-23'
 '2020-11-24' '2020-11-25']


In [ ]:
def date_array(start: str, end: str):
    if type(start) != str or type(end) != str:
        raise TypeError

    total_days_of_month = {"01": 31, "02": 28, "03": 31, "04":30, "05": 31, "06":30, "07":31, "08":31, "09":30, "10": 31, "11":30, "12":31}

    end = end.split("-")
    end_last = int(end[-1]) + 1

    # If the next day of end falls in the next month, account for that
    if total_days_of_month[end[-2]] < end_last:
        days_diff = end_last - total_days_of_month[end[-2]]
        end[-1] = f'0{days_diff}' if days_diff< 10 else f'{days_diff}'
        next_month = int(end[-2]) + 1
        end[-2] = f'0{next_month}' if next_month< 10 else f'{next_month}'
    else:
        end[-1] = f'0{end_last}' if end_last < 10 else f'{end_last}'
    end = "-".join(end)
    return np.arange(start, end, dtype="datetime64[D]")    # Use arange() to generate all dates between start and end
date_array(start = '2020-11-25', end = '2020-11-30')

array(['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
       '2020-11-29', '2020-11-30'], dtype='datetime64[D]')

###`Q-14:` Subtract the mean of each row from a matrix.

In [ ]:
#code here
x = np.random.random((5,4))
x-x.mean(axis=1,keepdims=True)

array([[-0.28908057,  0.16611322,  0.07388319,  0.04908416],
       [ 0.21387574,  0.23805003, -0.14504909, -0.30687668],
       [-0.41817536,  0.31260251, -0.22265218,  0.32822503],
       [-0.2313321 ,  0.16898547,  0.0842564 , -0.02190977],
       [ 0.18156414,  0.30363652, -0.16551927, -0.31968139]])

###`Q-15:` Swap column-1 of array with column-2 in the array.

In [ ]:
#Code here
a = np.arange(9).reshape(3,3)
a[:,[0,2,1]]

array([[0, 2, 1],
       [3, 5, 4],
       [6, 8, 7]])

###`Q-16:` Replace odd elements in arrays with -1.

In [ ]:
#Code here
a = np.arange(10)
a[a%2==1] = -1
a

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

###`Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

In [ ]:
#Code here
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])
a[b>a] = b[a<b]
a

array([6, 3, 1, 7, 8])

###`Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [ ]:
# Given
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr1

array([[4702, 3669,  396, 7537, 6498],
       [6136, 5433, 2797, 4856, 2115],
       [ 873, 1228, 3738, 1588, 8812],
       [9185, 1090,  775, 3924, 4749],
       [5856, 7330, 4108, 3479, 2218],
       [6301,  222, 2565, 8990, 4672],
       [4541, 5725, 4977,  753, 7163],
       [9286, 6559, 9132, 7246, 8401]])

In [ ]:
#Code here
arr1[:,::2]

array([[4702,  396, 6498],
       [6136, 2797, 2115],
       [ 873, 3738, 8812],
       [9185,  775, 4749],
       [5856, 4108, 2218],
       [6301, 2565, 4672],
       [4541, 4977, 7163],
       [9286, 9132, 8401]])

In [ ]:
(arr1 - arr1.min())/(arr1.max()-arr1.min())

array([[0.49426302, 0.38029568, 0.01919682, 0.80703883, 0.69240953],
       [0.65247132, 0.57491174, 0.28409091, 0.51125331, 0.20884819],
       [0.07182259, 0.11098853, 0.38790821, 0.15070609, 0.94770521],
       [0.98885702, 0.09576346, 0.06101059, 0.40842895, 0.49944837],
       [0.62157988, 0.78420124, 0.42872904, 0.35933363, 0.22021183],
       [0.6706752 , 0.        , 0.25849515, 0.96734334, 0.49095322],
       [0.47650044, 0.6071271 , 0.52460282, 0.05858341, 0.7657767 ],
       [1.        , 0.69913945, 0.98300971, 0.7749338 , 0.90236099]])

###`Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [ ]:
#Code here
def nthmax(arr,n):
  if n>len(arr):
    raise IndexError("n is way out of limit")
  arr.sort()
  return arr[-n]
nthmax(np.array([12,34,40,7,1,0]),2)

34

###`Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [ ]:
#code here
a = np.array([1,2,3])
np.hstack([np.repeat(a,3),np.tile(a,3)])

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])